"""Initial schema

Revision ID: 8020591fca1a
Revises:
Create Date: 2026-03-21 10:58:33.928551

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "8020591fca1a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "torrent_downloads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("magnet_uri", sa.String(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "DOWNLOADING", "COMPLETED", "FAILED", name="downloadstatus"
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("eta", sa.Integer(), nullable=True),
        sa.Column("save_path", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "downloaded_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("torrent_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("final_path", sa.String(), nullable=False),
        sa.Column("moved_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["torrent_id"],
            ["torrent_downloads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("downloaded_files")
    op.drop_table("torrent_downloads")
    # ### end Alembic commands ###
